
import com.mysql.jdbc.Connection;
//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naeem
 */
public class Adminmenu extends javax.swing.JFrame {

    /**
     * Creates new form Adminmenu
     */
    public Adminmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        menulogout = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Add Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        menulogout.setBackground(new java.awt.Color(0, 153, 153));
        menulogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menulogout.setText("Log out");
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulogoutMouseClicked(evt);
            }
        });
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Customer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Administrator");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(menulogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 120, 390, 590);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(385, 122, 720, 562);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseClicked
        
        this.dispose();
        Adminlogin l=new Adminlogin();
        l.setSize(1200,750);
        l.setVisible(true);
        l.setLocationRelativeTo(null); // TODO add your handling code here:
    }//GEN-LAST:event_menulogoutMouseClicked

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_menulogoutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
        try{
			 
			 Statement stmt=Connect.ConnectDB().createStatement();  
            try ( // String sql="select * from EMPDATA";
            // pst=con.prepareStatement(sql);
            // rs=pst.executeQuery();
                    ResultSet rs = stmt.executeQuery("select * from customer")) {
                table.setModel(DbUtils.resultSetToTableModel(rs));
                //JLabel lblNewLabel_1 = new JLabel("|   NAME       |    MOBILE     | ADDRESS    | TABLEno    | DATE-time     | CHICKLOL  |   CHICKT    |   PANNERT    | MANCHURIAN |    RICE     |     NAAN      |      DAL       |     KHADIP     |       CHICKM    |   DRINKS    |     HOME   |      SUB       |       GST        |      TOTAL   ");
                //lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 13));
                //lblNewLabel_1.setBounds(12, 156, 1557, 29);
                //contentPane.add(lblNewLabel_1);
            }
			 }
			 catch(Exception e){
			 JOptionPane.showMessageDialog(null, e.getMessage());
			 }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        this.dispose();
        adminregister l=new adminregister();
        l.setSize(1200,750);
        l.setVisible(true);
        l.setLocationRelativeTo(null);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
        try{
			 
			 Statement stmt=Connect.ConnectDB().createStatement();  
            try ( // String sql="select * from EMPDATA";
            // pst=con.prepareStatement(sql);
            // rs=pst.executeQuery();
                    ResultSet rs = stmt.executeQuery("select * from admin")) {
                table.setModel(DbUtils.resultSetToTableModel(rs));
                //JLabel lblNewLabel_1 = new JLabel("|   NAME       |    MOBILE     | ADDRESS    | TABLEno    | DATE-time     | CHICKLOL  |   CHICKT    |   PANNERT    | MANCHURIAN |    RICE     |     NAAN      |      DAL       |     KHADIP     |       CHICKM    |   DRINKS    |     HOME   |      SUB       |       GST        |      TOTAL   ");
                //lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 13));
                //lblNewLabel_1.setBounds(12, 156, 1557, 29);
                //contentPane.add(lblNewLabel_1);
            }
			 }
			 catch(Exception e){
			 JOptionPane.showMessageDialog(null, e.getMessage());
			 }


// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        try{
			 
			 Statement stmt=Connect.ConnectDB().createStatement();  
            try ( // String sql="select * from EMPDATA";
            // pst=con.prepareStatement(sql);
            // rs=pst.executeQuery();
                    ResultSet rs = stmt.executeQuery("select * from orders")) {
                table.setModel(DbUtils.resultSetToTableModel(rs));
                //JLabel lblNewLabel_1 = new JLabel("|   NAME       |    MOBILE     | ADDRESS    | TABLEno    | DATE-time     | CHICKLOL  |   CHICKT    |   PANNERT    | MANCHURIAN |    RICE     |     NAAN      |      DAL       |     KHADIP     |       CHICKM    |   DRINKS    |     HOME   |      SUB       |       GST        |      TOTAL   ");
                //lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 13));
                //lblNewLabel_1.setBounds(12, 156, 1557, 29);
                //contentPane.add(lblNewLabel_1);
            }
			 }
			 catch(Exception e){
			 JOptionPane.showMessageDialog(null, e.getMessage());
			 }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menulogout;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
