/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Naeem
 */
public class Custregister extends javax.swing.JFrame {

    /**
     * Creates new form Custregister
     */
    public Custregister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jlab = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        confirmpwd = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        aregisterback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Customer Registeration");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 130, 500, 70);

        jlab.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlab.setForeground(new java.awt.Color(153, 153, 153));
        jlab.setText("Name:");
        getContentPane().add(jlab);
        jlab.setBounds(240, 240, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Contact number:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 290, 220, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Email ID:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 340, 220, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 390, 220, 40);
        getContentPane().add(contact);
        contact.setBounds(530, 290, 500, 31);
        getContentPane().add(email);
        email.setBounds(530, 340, 500, 31);
        getContentPane().add(address);
        address.setBounds(530, 390, 500, 31);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Password must have alleast 8 character, one special character, one uppercase character, one lowercase character,one digit character !!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 430, 800, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("New Password:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 460, 220, 40);
        getContentPane().add(pwd);
        pwd.setBounds(530, 460, 500, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Confirm Password:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 500, 240, 40);
        getContentPane().add(confirmpwd);
        confirmpwd.setBounds(530, 510, 500, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Sign up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 570, 260, 70);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(530, 240, 500, 31);

        aregisterback.setBackground(new java.awt.Color(0, 153, 153));
        aregisterback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aregisterback.setText("Back");
        aregisterback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aregisterbackMouseClicked(evt);
            }
        });
        aregisterback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aregisterbackActionPerformed(evt);
            }
        });
        getContentPane().add(aregisterback);
        aregisterback.setBounds(160, 80, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1190, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Pattern pattern;
        Matcher matcher;
        boolean flag=true;

        String name1= name.getText();
        String cno= contact.getText();
        String mail=email.getText();
        String add=address.getText();
        String pass,cpass;

        ArrayList<String> errorList = new ArrayList<>();

        pass=String.valueOf(pwd.getPassword());
        cpass=String.valueOf(confirmpwd.getPassword());

        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        pattern = Pattern.compile(EMAIL_PATTERN);

        matcher=pattern.matcher(mail);

        boolean valid = true;

        if (cno.length() != 10)
        {
            errorList.add("Contact number should be 10 characters in length.");
            valid = false;
        }

        if(!matcher.matches()){
            errorList.add("Invalid E-mail");
            valid=false;

        }
        if (!pass.equals(cpass)) {
            errorList.add("password and confirm password does not match");
            valid=false;
        }
        if (pass.length() < 8)
        {
            errorList.add("Password should be more than 8 characters in length.");
            valid = false;
        }

        String upperCaseChars = "(.*[A-Z].*)";
        if (!pass.matches(upperCaseChars ))
        {
            errorList.add("Password should contain atleast one upper case alphabet");
            valid = false;
        }
        String lowerCaseChars = "(.*[a-z].*)";
        if (!pass.matches(lowerCaseChars ))
        {
            errorList.add("Password should contain atleast one lower case alphabet");
            valid = false;
        }
        String numbers = "(.*[0-9].*)";
        if (!pass.matches(numbers ))
        {
            errorList.add("Password should contain atleast one number.");
            valid = false;
        }
        String specialChars = "(.*[,~,!,@,#,$,%,^,&,*,(,),-,_,=,+,[,{,],},|,;,:,<,>,/,?].*$)";
        if (!pass.matches(specialChars ))
        {
            errorList.add("Password should contain atleast one special character");
            valid = false;
        }
        
         try{
                              
                                double cn=Double.parseDouble(cno);
                       
                                                           
                                 }catch(NumberFormatException e)
                                 {
                                     contact.setText(null);
                                      errorList.add("invalid mobile number entered");
                                     valid=false;
                                 
                                 }

        if(!valid){
            pwd.setText("");
            confirmpwd.setText("");
            email.setText("");
            JOptionPane.showMessageDialog(null,errorList);
            errorList.clear();
        }

        if(name1.equals("")||cno.equals("")||mail.equals("")||add.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(null,"No field should be empty");
        }
        if (valid)
        {

            PreparedStatement ps;
            String query= "insert into customer (cname,cno,email,address,pwd) values(?,?,?,?,?)";

            try {
                ps= Connect.ConnectDB().prepareStatement(query);

                ps.setString(1,name1);
                ps.setString(2,cno);
                ps.setString(3,mail);
                ps.setString(4,add);
                ps.setString(5,pass);

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"new Customer added");

                }

            } catch (SQLException ex) {

            }
            name.setText("");
            contact.setText("");
            email.setText("");
            address.setText("");
            pwd.setText("");
            confirmpwd.setText("");

            this.dispose();
            Customerlogin c=new Customerlogin();
            c.setSize(1200,750);
            c.setVisible(true);
            c.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void aregisterbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aregisterbackMouseClicked
        Customerlogin l=new Customerlogin();
        l.setSize(1200,750);
        l.setVisible(true);
        l.setLocationRelativeTo(null); // TODO add your handling code here:
    }//GEN-LAST:event_aregisterbackMouseClicked

    private void aregisterbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aregisterbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aregisterbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Custregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Custregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Custregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Custregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton aregisterback;
    private javax.swing.JPasswordField confirmpwd;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlab;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables
}
