/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.print.PrinterException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.JSType;

/**
 *
 * @author Naeem
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    String username,passw;
    public Menu(String usr,String pass){
        this.username=usr;
        this.passw=pass;
    }    
     
    public Menu() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qtyrice = new javax.swing.JTextField();
        qtynaan = new javax.swing.JTextField();
        qtydal = new javax.swing.JTextField();
        qtykhadi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        qtychicken = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        qtyclol = new javax.swing.JTextField();
        qtyct = new javax.swing.JTextField();
        qtypt = new javax.swing.JTextField();
        qtyman = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        asubtotal = new javax.swing.JTextField();
        btnrec = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        print = new javax.swing.JButton();
        agst = new javax.swing.JTextField();
        atotal = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        menulogout = new javax.swing.JButton();
        hdel = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        qtydrink = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        finalrec = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Main Course");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Qty");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Items");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Price");

        qtyrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyrice.setText("0");

        qtynaan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtynaan.setText("0");

        qtydal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtydal.setText("0");

        qtykhadi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtykhadi.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Jeera Rice");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Naan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Paneer Kadhai");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Dal Tadka");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("70/-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("15/-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("100/-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("90/-");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Chicken kadhai");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("140/-");

        qtychicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtychicken.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8))
                                        .addGap(94, 94, 94)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel25))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel11)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtynaan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyrice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtydal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtykhadi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtychicken, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(qtyrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(qtynaan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(qtydal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(qtykhadi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtychicken, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(464, 125, 408, 351);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));
        jPanel3.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Starters");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Qty");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Items");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Price");

        qtyclol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyclol.setText("0");

        qtyct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyct.setText("0");

        qtypt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtypt.setText("0");

        qtyman.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyman.setText("0");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Chikken lolipop");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Chikken tikka");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Manchurian");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("Paneer tikka");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("120/-");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("90/-");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("60/-");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("75/-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel21))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtyct, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyclol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtypt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyman, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyclol, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtypt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyman, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(22, 125, 424, 351);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 8));
        jPanel4.setOpaque(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Amount");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        asubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnrec.setBackground(new java.awt.Color(0, 153, 153));
        btnrec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnrec.setText("Receipt");
        btnrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btntotal.setBackground(new java.awt.Color(0, 153, 153));
        btntotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(0, 153, 153));
        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("Print");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        agst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        atotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("Subtotal");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("GST");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(print, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(asubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(agst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(atotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(464, 481, 408, 230);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel5.setOpaque(false);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 153, 153));
        jLabel38.setText("Address:");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 153, 153));
        jLabel39.setText("Contact number:");

        mob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        ad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(153, 153, 153));
        jLabel40.setText("Name:");

        na.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mob, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ad))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(27, 27, 27)
                        .addComponent(na)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 590, 428, 120);

        menulogout.setBackground(new java.awt.Color(0, 153, 153));
        menulogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menulogout.setText("Log out");
        menulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulogoutMouseClicked(evt);
            }
        });
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        getContentPane().add(menulogout);
        menulogout.setBounds(1000, 70, 110, 30);

        hdel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hdel.setForeground(new java.awt.Color(153, 153, 153));
        hdel.setText("Home Delivery");
        hdel.setOpaque(false);
        getContentPane().add(hdel);
        hdel.setBounds(930, 140, 161, 31);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(330, 10, 259, 110);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel6.setOpaque(false);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("Drinks:");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("Qty");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("Items");

        qtydrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtydrink.setText("0");

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink", "Apple juice", "Tea", "Cola", "Cok", "Coffee", "Ice tea", "Ice coffee", "Orange juice" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel36))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtydrink, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtydrink, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 480, 430, 100);

        finalrec.setColumns(20);
        finalrec.setRows(5);
        finalrec.setText("\n");
        jScrollPane1.setViewportView(finalrec);

        jTabbedPane1.addTab("RECEIPT", jScrollPane1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(880, 180, 310, 530);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tim-mossholder-678979-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 1200, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulogoutMouseClicked
        
        this.dispose();
        Customerlogin l=new Customerlogin();
        l.setSize(1200,750);
        l.setVisible(true);
        l.setLocationRelativeTo(null); // TODO add your handling code here:
    }//GEN-LAST:event_menulogoutMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
       
    }//GEN-LAST:event_printMouseClicked

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_menulogoutActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        

			 	
				 				 
				 
                        double chicklol= Double.parseDouble(qtyclol.getText());
			double costc=120;
			double chick =(chicklol*costc);
			//String cmeal=String.format("%.2",chick);
			String cmeal=Double.toString(chick);
			asubtotal.setText(cmeal);	
			
			double ctika= Double.parseDouble(qtyct.getText());
			double costct=90;
			double chicktika =(ctika*costct);
			
			String ct=Double.toString(chicktika+chick);
			asubtotal.setText(ct);	
			
			double ptika= Double.parseDouble(qtypt.getText());
			double costpt=70;
			double pantika =(ptika*costpt);
			
			String pt=Double.toString(pantika+chick+chicktika);
			asubtotal.setText(pt);	
			
			double man= Double.parseDouble(qtyman.getText());
			double costman=60;
			double manchurian =(man*costman);
			
			String m=Double.toString(manchurian +pantika+chick+chicktika);
			asubtotal.setText(m);	
			
			double rice= Double.parseDouble(qtyrice.getText());
			double costrice=70;
			double rrice =(rice*costrice);
			
			String r=Double.toString(rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(r);	

			double naan= Double.parseDouble(qtynaan.getText());
			double costn=15;
			double naa =(naan*costn);
			
			String n=Double.toString(naa+rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(n);	
			
			double dal= Double.parseDouble(qtydal.getText());
			double costd=90;
			double dall =(dal*costd);
			
			String d=Double.toString(dall+naa+rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(d);	
			
			double khadi= Double.parseDouble(qtykhadi.getText());
			double costk=100;
			double pk =(khadi*costk);
			
			String kk=Double.toString(pk+dall+naa+rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(kk);	
			
			double chi= Double.parseDouble(qtychicken.getText());
			double costch=140;
			double ch =(chi*costch);
			
			String cc=Double.toString(ch+pk+dall+naa+rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(cc);	
			
			double costdel = 50;
			if(hdel.isSelected())
			{
				//String ddel= String.format("%.2f", costdel);
				String ddel=Double.toString(costdel+ch+pk+dall+naa+rrice+manchurian +pantika+chick+chicktika);
				asubtotal.setText(ddel);	
				
			}
			
			else
			{	
				String ddel=Double.toString(0+ch+pk+dall+naa+rrice+manchurian +pantika+chick+chicktika);
			asubtotal.setText(ddel);	
			}
			
		//-----------------------------------------------------------------------------------drinks	
			double dr= Double.parseDouble(qtydrink.getText());
			double apple=40*dr;
			double tea=10*dr;
			double cola=15*dr;
			double coke=15*dr;
			double coffee=15*dr;
			double itea=15*dr;
			double icoffee=20*dr;
			double orange=30*dr;
			
			if(cb.getSelectedItem().equals("Apple juice"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String aj=Double.toString(apple+a);
				asubtotal.setText(aj);
				
			}
			
			if(cb.getSelectedItem().equals("Tea"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String ttt=Double.toString(tea+a);
				asubtotal.setText(ttt);
				
			}
			
			if(cb.getSelectedItem().equals("Cola"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String co=Double.toString(cola+a);
				asubtotal.setText(co);
				
			}
			if(cb.getSelectedItem().equals("Coke"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String ck=Double.toString(coke+a);
				asubtotal.setText(ck);
				
			}
			
			if(cb.getSelectedItem().equals("Coffee"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String aj=Double.toString(coffee+a);
				asubtotal.setText(aj);
				
			}
			
			if(cb.getSelectedItem().equals("Ice Tea"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String aj=Double.toString(itea+a);
				asubtotal.setText(aj);
				
			}
			
			if(cb.getSelectedItem().equals("Ice Coffee"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String aj=Double.toString(icoffee+a);
				asubtotal.setText(aj);
				
			}
			
			if(cb.getSelectedItem().equals("Orange juice"))
			{   
				double a= Double.parseDouble(asubtotal.getText());
				String aj=Double.toString(orange+a);
				asubtotal.setText(aj);
				
			}
			
			
	//-------------------------------------------------------------------------------------------gst		
			double gs= Double.parseDouble(asubtotal.getText());
			double vat= (gs*0.12);
			String sg=Double.toString(vat);
			agst.setText(sg);
	//------------------------------------------------------------------------------------------total
			
			double t= Double.parseDouble(asubtotal.getText());
			double tt= Double.parseDouble(agst.getText());
			String to= Double.toString(t+tt);
			atotal.setText(to);
			
                   /*     ResultSet rs = null;
                        PreparedStatement pst = null;
			String sql = "select * from customer where cname = ? and pwd = ?";
        try {
            pst = Connect.ConnectDB().prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, passw );
            rs = pst.executeQuery();
           
                                         
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }*/
       
                        Matcher matcher;
			
			  DateFormat df = new SimpleDateFormat("dd/MM/yy  - HH:mm:ss");
                            Date dateobj = new Date();
		       
		       Random rand = new Random(); 
		        int status=1;
		        int ra = rand.nextInt(50); 
			String a=ad.getText();
			String name=na.getText();
		        String mo=mob.getText();
                       
                       
                        try{
                              
                                double cno=Double.parseDouble(mo);
                       
                                                           
                                 }catch(NumberFormatException e)
                                 {JOptionPane.showMessageDialog(this,"invalid mobile number entered","ERROR",JOptionPane.ERROR_MESSAGE);
                                  asubtotal.setText(null);
                                     agst.setText(null);
                                     atotal.setText(null);
                                     status=0;
                                 
                                 }
                        if(mob.getText().length()==10)
                        {	
		       
                        if(t<0){status=0;
                          asubtotal.setText(null);
                          agst.setText(null);
                          atotal.setText(null);
                          JOptionPane.showMessageDialog(null,"invalid quantity entered");
                        
                        }
                        if(mo.equals("")||a.equals("")||name.equals(""))
                                          {
                                              status=0;
                                              JOptionPane.showMessageDialog(null,"Enter name, contact number and address.");
                                          }
                        
		        if(status==1){
			try {
				 Class.forName("com.mysql.jdbc.Driver");
				 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root", "naeem00786" );
				 double i; 
				 Statement stmt=con.createStatement();  
				 if(hdel.isSelected())
				 {
					 i =1;}
				 else {
					   i=0;
				 }
				 String sqlquery="insert into orders values('"+name+"','"+mo+"','"+a+"','"+ra+"','"+df.format(dateobj)+"','"+chicklol+"','"+ctika+"','"+ptika+"','"+man+"','"+rice+"','"+naan+"','"+dal+"','"+khadi+"','"+chi+"','"+dr+"','"+i+"','"+t+"','"+tt+"','"+to+"')";
				 stmt.executeUpdate(sqlquery);
				
				
				 
			//	 ResultSet rs=stmt.executeQuery("select * from student order by marks");
			//	 while(rs.next())  
			//	 System.out.println(rs.getInt(1)+"  "+rs.getString(2)+"  "+rs.getString(3)+"   "+rs.getString(4));  
				 con.close();  
				 }catch(Exception ee){ System.out.println(ee);}  	
			
			
			
                        }
			
                        }
  else
                              JOptionPane.showMessageDialog(null,"MOBILE NUMBER SHOULD BE 10 DIGITS LONG");

// TODO add your handling code here:
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecActionPerformed
                
            finalrec.setText(null);
        double qty = Double.parseDouble(qtyclol.getText());
                        /*ResultSet rs = null;
                        PreparedStatement pst = null;
                        String sql = "select * from customer where cname = ? and pwd = ?";
                                  try {
                                        pst = Connect.ConnectDB().prepareStatement(sql);
                                            pst.setString(1, username);
                                            pst.setString(2, passw );
                                            rs = pst.executeQuery();
                                            
                                           
                                           
                                        } catch (SQLException ex) {
                                            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                                        }*/
				
				double qty1 = Double.parseDouble(qtyct.getText());
				double qty2 = Double.parseDouble(qtypt.getText());
				double qty3 = Double.parseDouble(qtyman.getText());
				double qty4 = Double.parseDouble(qtydrink.getText());
				double qty5 = Double.parseDouble(qtydal.getText());
				double qty6 = Double.parseDouble(qtyrice.getText());
				double qty7 = Double.parseDouble(qtychicken.getText());
				double qty8 = Double.parseDouble(qtynaan.getText());
				double qty9 = Double.parseDouble(qtykhadi.getText());
				double qty10 = Double.parseDouble(asubtotal.getText());
				double qty11 = Double.parseDouble(atotal.getText());
				double qty12 = Double.parseDouble(agst.getText());
                                
				//double qty13 = Double.parseDouble(qtydrink.getText());
				
				
				
				
				
				
				
				
				
				double chicklol= Double.parseDouble(qtyclol.getText());
				double costc=120;
				double chick =(chicklol*costc);
					
				
				double ctika= Double.parseDouble(qtyct.getText());
				double costct=90;
				double chicktika =(ctika*costct);
				
				
				
				double ptika= Double.parseDouble(qtypt.getText());
				double costpt=70;
				double pantika =(ptika*costpt);
				
				
				
				double man= Double.parseDouble(qtyman.getText());
				double costman=60;
				double manchurian =(man*costman);
				
				
				
				double rice= Double.parseDouble(qtyrice.getText());
				double costrice=70;
				double rrice =(rice*costrice);
				
				

				double naan= Double.parseDouble(qtynaan.getText());
				double costn=15;
				double naa =(naan*costn);
				
				
				double dal= Double.parseDouble(qtydal.getText());
				double costd=90;
				double dall =(dal*costd);
				
				
				double khadi= Double.parseDouble(qtykhadi.getText());
				double costk=100;
				double pk =(khadi*costk);
				
				
				
				double chi= Double.parseDouble(qtychicken.getText());
				double costch=140;
				double ch =(chi*costch);
				
				
				double dr= Double.parseDouble(qtydrink.getText());
				double cola=15*dr;
				
		//-------------------------------------------date and time
					       DateFormat df = new SimpleDateFormat("dd/MM/yy  - HH:mm:ss");
					       Date dateobj = new Date();
					       
					       Random rand = new Random(); 
					       
					        int ra = rand.nextInt(50); 
                                                int status=0;
                                                String n=na.getText();
                                                String m=mob.getText();
                                                String a=ad.getText();
					  	
                                                if(m.equals("")||a.equals("")||n.equals(""))
                                          {
                                              status=1;
                                              JOptionPane.showMessageDialog(null,"Enteontact number name, cr and address.");
                                          }
			if(status==0)	{
			finalrec.append("\t\n Restaurant food bill:\n"+"date and time: "+df.format(dateobj)+"      TAble no.   "+ra+"\t\n WELCOME\n -----------------------------------------------------------------------------"
			       +"\n CUSTOMER'S NAME:    "+n
			       +"\n CUSTOMER'S MOBILE NO:"+ m
			       +"\n  ADDRESS :"+a
			       +"\n-----------------------------------------------------------------------------"
			       +"\n\n     ITEMS   \t\t QTY      PRICE");
			       if(qty!=0)
			    	   finalrec.append("\n Chicken Lolipop:\t"+qty+"      "+chick);
			       
			       if(qty1!=0)
			    	   finalrec.append("\n Chicken Tika:  \t\t"+qty1+"      "+chicktika);
			       
			       if(qty2!=0)
			    	   finalrec.append("\n Panneer Tika:   \t"+qty2+"      "+pantika);
			       
			       if(qty3!=0)
			    	   finalrec.append("\n Manchurian:    \t\t"+qty3+"      "+manchurian);
			       
			       if(qty5!=0)
			    	   finalrec.append("\n Dal Makhani:   \t\t"+qty5+"      "+dall);
			       
                   if(qty6!=0)
                	   finalrec.append("\n jeera Rice:    \t\t"+qty6+"      "+rrice);
                   
			       if(qty7!=0)
			    	   finalrec.append("\n Chicken mashla: \t"+qty7+"      "+ch);
			       
			       if(qty8!=0)
			    	   finalrec.append("\n Naan:          \t\t"+qty8+"      "+naa);
			       
			       if(qty9!=0)
			    	   finalrec.append("\n khadhi panneer: \t"+qty9+"      "+pk);
			       if(qty4!=0)
			    	   finalrec.append("\n Drinks:        \t\t"+qty4+"      "+cola);
			       
			       finalrec.append("\n-------------------------------------------------------------------------------"
			       +"\nSUB TOTAL :     \t\t   RS."+qty10
			       +"\n GST:           \t\t   RS."+qty12
			       +"\nTOTAL:          \t\t   RS."+qty11+
			       
			       "\n-----------------------------------------------------------------------------------"+
			       "\n\n THANKYOU \n VISIT AGAIN:\t"+
			       "\n\n rate us on www.foodtasteindia.com"
					
					
				
					
					);	
			       if( hdel.isSelected())
			       {
			    	   finalrec.append("\n HOME DELIVERY");
			       }
                        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnrecActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        qtyclol.setText("0");
				qtyct.setText("0");
				qtypt.setText("0");
				qtyman.setText("0");
				qtydrink.setText("0");
				qtydal.setText("0");
				qtyrice.setText("0");
				qtychicken.setText("0");
				qtynaan.setText("0");
				qtykhadi.setText("0");
				asubtotal.setText("0");
				atotal.setText("0");
                                agst.setText("0");
				cb.setSelectedItem("Select a drink");
			//	subt.setText(null);
				finalrec.setText(null);
				
				hdel.setSelected(false); 

        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

                                try
				{ finalrec.print();
				
				}catch(PrinterException e)
				{
					
				}

        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField agst;
    private javax.swing.JTextField asubtotal;
    private javax.swing.JTextField atotal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnrec;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextArea finalrec;
    private javax.swing.JCheckBox hdel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton menulogout;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField na;
    private javax.swing.JButton print;
    private javax.swing.JTextField qtychicken;
    private javax.swing.JTextField qtyclol;
    private javax.swing.JTextField qtyct;
    private javax.swing.JTextField qtydal;
    private javax.swing.JTextField qtydrink;
    private javax.swing.JTextField qtykhadi;
    private javax.swing.JTextField qtyman;
    private javax.swing.JTextField qtynaan;
    private javax.swing.JTextField qtypt;
    private javax.swing.JTextField qtyrice;
    // End of variables declaration//GEN-END:variables
}
