/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naeem
 */
public class Restor extends javax.swing.JFrame {

    /**
     * Creates new form Restor
     */
    public Restor() {
        initComponents();
        setSize(1200,750); 
         setLocationRelativeTo(null); 
         
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerlogin = new javax.swing.JButton();
        adminlogin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(null);

        customerlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        customerlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.png"))); // NOI18N
        customerlogin.setText("Customer Login");
        customerlogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        customerlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerlogin.setOpaque(false);
        customerlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerloginMouseClicked(evt);
            }
        });
        customerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerloginActionPerformed(evt);
            }
        });
        getContentPane().add(customerlogin);
        customerlogin.setBounds(331, 259, 240, 227);

        adminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.jpg"))); // NOI18N
        adminlogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        adminlogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adminlogin.setOpaque(false);
        adminlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminloginMouseClicked(evt);
            }
        });
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(adminlogin);
        adminlogin.setBounds(680, 260, 230, 227);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(930, 90, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 120, 250, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1190, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerloginActionPerformed
       
    
     
             
             // TODO add your handling code here:
    }//GEN-LAST:event_customerloginActionPerformed

    private void customerloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerloginMouseClicked
       this.dispose();
        Customerlogin c=new Customerlogin();
       c.setSize(1200,750);
        c.setVisible(true);
        c.setLocationRelativeTo(null);
// TODO add your handling code here:
    }//GEN-LAST:event_customerloginMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminloginActionPerformed

    private void adminloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminloginMouseClicked
      this.dispose();
      Adminlogin a=new Adminlogin();
      a.setSize(1200,750);
      a.setVisible(true);
      a.setLocationRelativeTo(null);
// TODO add your handling code here:
    }//GEN-LAST:event_adminloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin;
    private javax.swing.JButton customerlogin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
